# -*- coding: utf-8 -*-
"""Day0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Uq0NteJezUfXIufKYO3TRjKhu0oovGlj

# What is Python?

* Python is an interpreted, high-level and general-purpose programming language.
* object-oriented approach aim to help programmers write clear
* dynamically typed and garbage-collected.
* Python was created in the late 1980s by Guido van Rossum
"""

print("Hello World!")

print('Hello World')

print("Hello1")
print("Hello2")
print("Hello3")
print("Welcome to Our Python course")

print "Hello World"

print(Hello)

print("Hello')

"""### Comments"""

#taking some notes 
#taking some notes
#take a note

'''Michael Irwin Jordan is an American scientist, professor at the University of California, 
Berkeley and researcher in machine learning, statistics, and artificial intelligence.
He is one of the leading figures in machine learning, 
and in 2016 Science reported him as the world's most influential computer scientist.
'''.replace("\n"," ")

"""write something

### Declaring Variables

* variable = value

* n = 5
"""

n = 1 
print(n)

p = n
print(p)

"""### Data Types
* Integer
* Float
* String
* Boolean
* Complex
* Dictionary
* Tuple
* Set

"""

#String
hello = "World"

print(hello) #print variable
print("World") #print value
print(n)

#type() 
type(hello)

print(type(hello)) #print data type

#Integer
int_value = 5
int_value

print(type(int_value))

t = 3.19
print(type(t))

type('x')

#Boolean
t, f = True, False
print(type(t))
print(t)
print(f)

#swapping
data1 = 7 
data2 = 12
data3 = 23
data4 = 33

data1, data2, data3 , data4 = data2 , data1, data4, data3
print(data1, data2, data3, data4)

print("data1:", data1, "data:", data2)

#length ifadesi bir string değerin uzunluğunu bulmamıza yarar.
len("Pythoneer")

len("Welcome to Turkish AI Hub")

hello

print(len(hello)) #print data length

p

len(5)

len(15.6)

data22 = "Data Science"
len(data22)

len("Data Science")

a = 15
b = 23

a, b = b, a
print(a)
print(b)

#F-string
name = "Turkey"
print(f'hello {name}')

print("Hello", name)

name2 = "Aslı"
print("Hello {}".format(name2))

data12 = 5
data13 = 90
print("My value:{} and Your value:{}".format(data12, data13))

print(f'My value: {data12} and your value: {data13}')

print("My value:" + str(data12) + "Your Value:" + str(data13))

a = 50

type(a)

type(str(a))

type(a)

a = str(a)

a

type(a)

"""## Aritmetic Operations"""

#exponential numbers
5**2

5**3

35+67

"35"+"67"

"Omer" + "Cengiz"

"35" + 67

"35"*3

"hello"*4

"hello" "world"

x = 10

print(x+2)
print(x-2)
print(x*2)
print(x**2)
print(x**4)
print(x/2)
print(x//2) 
print(x%2)

y = 13
print(y/2)
print(y//2)
print(y % 2)

z = 5
z+=1 # this statement equals to z= z+1 , meaning while the previous value of z is 5, the new z value becomes 6. 
z

z +=2 #z = z + 2
z

z*=2      # z = z * 2
z