# -*- coding: utf-8 -*-
"""Day2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fyOOwwnpAGiUfDf47RB0KUc9Vm4Vm2aM

# Lists
"""

# creating a list
mylist = [3,5,6,7]
print(mylist)

type(mylist)

print(mylist[0])
print(mylist[2])
print(mylist[-1])
print(mylist[-3])

mylist[2] = "python"   # lists can be taken different types of data
print(mylist)

mylist.append('course')  # append(): adding some items end of the list 
print(mylist)

mylist = [3,4,5,6,7]
mylist.append('course')
mylist.append('course')
print(mylist)

thelast = mylist.pop()  # pop(): removing the last item of the list 
print(thelast)
print(mylist)

mylist.index("course")

mylist.index(4)

mylist.count("course")

list2 = ["Python","Java","R","JavaScript","Ruby","Python","Python"]
list2.count("Python")

mylist.remove("course")
print(mylist)

list3 = [100,23,87,13,1000]
list3.sort()
list3

list4 = [41,23,78,99,37,2.9,2.8]
list4.sort()
list4

list4.remove()

list5 = [41,23,78,99,37,'python']
list5.sort()
list5

mylist.remove("course")
mylist.remove("python")
print(mylist)

mylist = [3,4,5,6,7]
mylist.reverse()
mylist

mylist[::-1]

mylist2 = ["python", "course", "hello"]
mylist2.sort()
mylist2

mylist3 = [1, 11, 111, 1111]
mylist.extend(mylist3)
mylist

mylist4 = [1, 11, 111, 1111]
mylist.append(mylist4)
print(mylist)

list_in_list = ["python","Java",3.2, 4, 11, [5,65,7,8,9]]
print(list_in_list[5])

list_in_list[-1]

mylist = [2, 3, 4, 5, 6, 'python', 'flutter', 'Android', 'JavaScript', 'dart', 3.2, 5.0]
print(mylist)

mylist.insert(5,55)   # insert(x,y) --> adding x th index the y value but don't change the x th value, it remains the same.
print(mylist)

a = list([1,2,3,4,5,6])
a

liste1 = list()
numbers = list(range(8))

print(numbers)
print(liste1)

numbers2 = list(range(2,15,3)) #range(start, stop, step)
print(numbers2)
numbers2.reverse()
print(numbers2)

print(numbers[2:5])

numbers[5:8] = [10,11,12]
numbers

12 in numbers

15 in numbers

[1,2,3] + [4,5]

[1,2,3] * 3

list1 = [[1,2], 3, [4,5,6]]
list1[1]

"""# Conditional Statements 

## If

if "condition":


> "do something"   


print()
"""

num = int(input("Please enter a number: "))

if num < 0:  
  num *= -1  #num = num*-1
print("Result: ", num)

"""# If-Else

if "condition":


> "do something" 

else:



> "do something another" 



print()

# If-Elif-Else

if "condition":


> "do something"  

elif "condition-2":



> "do something another" 

elif "condition-3":



> "do something another" 





else:



> "do something different" 



print()
"""

score = int(input("Please enter your score: "))

if score <= 40:
  print("Very bad, you should work hard..")
elif score <= 60:
  print("Nice but you should work more..")
elif score <= 100:
  print("Congratulation!")
else:
  print("Invalid score!!!")

x = 8

if x > 4:
  x = x+1
elif x > 5:
  x = x+2
elif x > 7:
  x = x+3

print ("x, ", x)

x = 5

if x > 4:
  x = x+1

if x > 5:
  x = x+2

if x > 7:
  x = x+3

print ("x, ", x)

print("**************ATM Giriş Paneli**************")

kullanici_adi = "Omer"
parola ="hello"

kullanici_adi1 =input("Lütfen kullanıcı adınızı giriniz")

parola1= input("Lütfen Parolanızı giriniz.")

if (kullanici_adi != kullanici_adi1 and parola == parola1):
    print("Kullanıcı adınız hatalı")
elif (kullanici_adi==kullanici_adi1 and parola != parola1):
    print("Parolanız hatalı")
elif (kullanici_adi != kullanici_adi1 and parola!= parola1):
    print("Kullanıcı adınız ve parolanız hatalıdır.")
else:
    print("Tebrikler, Başarıyla giriş yaptınız")

x = 10

if x > 5:
    if x >7:
        print("İlker and Eylül")

"""# Question

At a particular company, employees’ salaries are raised progressively, calculated using the following formula:

salary = salary + salary x (raise percentage) 

Raises are predefined as given below, according to the current salary of the worker. For instance, if the worker’s current salary is less than or equal to 1000 TL, then its salary is increased 15%.


Range | Percentage
--- | ---
0 < salary ≤ 1000 | 15%
1000 < salary ≤ 2000 |10%
2000 < salary ≤ 3000| 5%
3000 < salary | 2.5%


Write a program that asks the user to enter his/her salary. Then your program should calculate and print the raised salary of the user.

Some example program runs:

Please enter your salary: 1000

Your raised salary is 1150.0.

Please enter your salary: 2500

Your raised salary is 2625.0.

# Answer
"""

salary = float(input("Please enter your salary: "))

if salary < 0:
  print("Invalid value")
else:

  if 0 < salary <= 1000:
    salary = salary + salary * 0.15
  elif salary <= 2000:
    salary = salary + salary * 0.1
  elif salary <= 3000:
    salary = salary + salary * 0.05
  else:
    salary = salary + salary * 0.025

  print("Your raised salary is", salary)

"""# While Loop Structure

Condition Intro

while <condition>:



> "true statement"

> "true statement"

> condition update


A logical condition is repeated as long as it has a logical true value. For ending the loop, that condition must become false. 



  
"""

num = 0

while num < 9:
  print("Value:{}".format(num))
  num = num +1

num2 = 0

while num2 != 9:
  print("Value:", num2)
  num2 +=2

#infinite loop

num3 = int(input("Please enter an integer between 1 and 10: "))

while num3 < 1 or num3 > 10:  
    print("Invalid value!!!!")
    sayi3 = int(input("Please enter an integer between 1 and 10: "))
print("Congrats...")

num3 = int(input("Please enter an integer between 1 and 10: "))

while num3 < 1 or num3 > 10:  
  print("Invalid value!!!!")
  num3 = int(input("Please enter an integer between 1 and 10: "))
    
    
print("Congrats!!...")

"""## Print items of a list """

t = [1,2,3,4,5,6]
len(t)

i = 0 #counter value

while (i < len(t)):
  #i+=1
  print(i, "th item: ", t[i])
  i+=1

while True:
  a = input("Enter a value: ")
  if a == "Exit":
    break

"""# For Loop Structure


for "repeated value" in "list":



> "true statement"




It takes the items as in sequence and processes them in a loop.



"""

"""
a[0]
a[1]
a[2]
"""


a = [2,45,57]

for i in a: 
  print(i)

i = 5
i in range(5)

list1 = list(range(5))
list1

list2 = list("Python")
list2

for i in range(5):
  print(i)

for i in "Python Course":
  print(i)

for i in "Python Course".split():
  print(i)

for i in range(10):
  if i == 5:    
    break
  print(i)

for i in range(10):
  if i == 5:
    continue
  print(i)

nums = list(range(8))

squares = []

for i in nums:
  squares.append(i**2)
print(squares)

nums = list(range(8))
print(nums)
squares = [i**2 for i in nums]
print(squares)

nums = list(range(8))

even_squares = [i**2 for i in nums if i % 2 == 0]

odd_squares = [i**3 for i in nums if i% 2 == 1]

print(even_squares)
print(odd_squares)

mylist = [3,5,12,7,65,35]

sum1 = 0

for i in mylist:
  sum1 = sum1 + i    #sum += i
  print(sum1)
    
print(sum1)
  #print(sum1)

"""### Built-in functions"""

list1 = [1,2,3]
list2 = [4,5,6]

list(zip(list1,list2))

list1 = [1,2,3]
list2 = [4,5,6]

list3 = [a + b for a,b in zip(list1,list2)]

print(list3)

"""### Find the max item of a list"""

mylist = [3,5,12,7,65,35]
print(mylist[0])

max1 = mylist[0]

for i in mylist:
    if i > max1:
        max1 = i
        print("max1: ", max1)
        print("i: ", i)
print(max1)